In [1]:
import funcionese as funcionese

In [2]:
df = funcionese.cargar_dataset("Victoria BC.csv")
df

,Unnamed: 0,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
0,0,19898,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/69729,NaN,NaN,f,6,"['email', 'phone']",...,1,0,1,0,NaN,Ryan,1,NaN,0,NaN
1,1,41168,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/173169,"Victoria, Canada",99%,t,6,"['email', 'phone']",...,3,3,0,0,0.50,Ocean Island Garden Suites,3,t,70,"$9,999.00"
2,2,83515,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/455118,"British Columbia, Canada",97%,t,4,"['email', 'phone']",...,2,2,0,0,0.89,Celia,2,t,148,$175.00
3,3,168460,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/802981,"Victoria, Canada",NaN,f,3,"['email', 'phone', 'work_email']",...,1,1,0,0,0.42,Deborah,1,t,64,$200.00
4,4,185732,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/880366,"Victoria, Canada",0%,f,3,"['email', 'phone', 'work_email']",...,3,0,3,0,0.32,Peter,3,t,52,$199.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3946,3946,1315368084757533488,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/548256873,NaN,100%,NaN,6,"['email', 'phone']",...,3,3,0,0,NaN,Swell West,6,t,0,$263.00
3947,3947,1316608634341666791,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/668062525,NaN,NaN,f,1,"['email', 'phone']",...,1,1,0,0,NaN,Charlotte Jane,1,t,0,$128.00
3948,3948,1317141084646533661,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/290549710,"Victoria, Canada",NaN,f,1,"['email', 'phone']",...,1,1,0,0,NaN,Majachani,1,NaN,0,$98.00
3949,3949,1318221712246054906,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/112019210,"Victoria, Canada",91%,t,4,['phone'],...,1,1,0,0,1.00,Troy,1,t,1,$61.00
3950,3950,1318259877390189592,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/32614142,"Victoria, Canada",98%,t,118,"['email', 'phone', 'work_email']",...,53,53,0,0,NaN,Elite Vacation Homes,55,t,0,$148.00

In [3]:
df = df.drop('Unnamed: 0', axis=1)
df

,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,longitude,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
0,19898,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/69729,NaN,NaN,f,6,"['email', 'phone']",-123.339770,...,1,0,1,0,NaN,Ryan,1,NaN,0,NaN
1,41168,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/173169,"Victoria, Canada",99%,t,6,"['email', 'phone']",-123.370650,...,3,3,0,0,0.50,Ocean Island Garden Suites,3,t,70,"$9,999.00"
2,83515,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/455118,"British Columbia, Canada",97%,t,4,"['email', 'phone']",-123.499960,...,2,2,0,0,0.89,Celia,2,t,148,$175.00
3,168460,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/802981,"Victoria, Canada",NaN,f,3,"['email', 'phone', 'work_email']",-123.367900,...,1,1,0,0,0.42,Deborah,1,t,64,$200.00
4,185732,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/880366,"Victoria, Canada",0%,f,3,"['email', 'phone', 'work_email']",-123.463570,...,3,0,3,0,0.32,Peter,3,t,52,$199.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3946,1315368084757533488,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/548256873,NaN,100%,NaN,6,"['email', 'phone']",-124.402109,...,3,3,0,0,NaN,Swell West,6,t,0,$263.00
3947,1316608634341666791,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/668062525,NaN,NaN,f,1,"['email', 'phone']",-123.414387,...,1,1,0,0,NaN,Charlotte Jane,1,t,0,$128.00
3948,1317141084646533661,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/290549710,"Victoria, Canada",NaN,f,1,"['email', 'phone']",-123.395233,...,1,1,0,0,NaN,Majachani,1,NaN,0,$98.00
3949,1318221712246054906,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/112019210,"Victoria, Canada",91%,t,4,['phone'],-123.545252,...,1,1,0,0,1.00,Troy,1,t,1,$61.00
3950,1318259877390189592,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/32614142,"Victoria, Canada",98%,t,118,"['email', 'phone', 'work_email']",-123.369628,...,53,53,0,0,NaN,Elite Vacation Homes,55,t,0,$148.00

In [4]:
df = funcionese.sustituir_nulos(df)
df

/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:29: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(1000001, inplace=True)
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna("Valor Nulo", inplace=True)
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:27: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(1111111, inplace=True)

,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,longitude,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
0,19898,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/69729,Valor Nulo,Valor Nulo,f,6,"['email', 'phone']",-123.339770,...,1,0,1,0,1000001.00,Ryan,1,Valor Nulo,0,Valor Nulo
1,41168,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/173169,"Victoria, Canada",99%,t,6,"['email', 'phone']",-123.370650,...,3,3,0,0,0.50,Ocean Island Garden Suites,3,t,70,"$9,999.00"
2,83515,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/455118,"British Columbia, Canada",97%,t,4,"['email', 'phone']",-123.499960,...,2,2,0,0,0.89,Celia,2,t,148,$175.00
3,168460,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/802981,"Victoria, Canada",Valor Nulo,f,3,"['email', 'phone', 'work_email']",-123.367900,...,1,1,0,0,0.42,Deborah,1,t,64,$200.00
4,185732,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/880366,"Victoria, Canada",0%,f,3,"['email', 'phone', 'work_email']",-123.463570,...,3,0,3,0,0.32,Peter,3,t,52,$199.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3946,1315368084757533488,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/548256873,Valor Nulo,100%,Valor Nulo,6,"['email', 'phone']",-124.402109,...,3,3,0,0,1000001.00,Swell West,6,t,0,$263.00
3947,1316608634341666791,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/668062525,Valor Nulo,Valor Nulo,f,1,"['email', 'phone']",-123.414387,...,1,1,0,0,1000001.00,Charlotte Jane,1,t,0,$128.00
3948,1317141084646533661,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/290549710,"Victoria, Canada",Valor Nulo,f,1,"['email', 'phone']",-123.395233,...,1,1,0,0,1000001.00,Majachani,1,Valor Nulo,0,$98.00
3949,1318221712246054906,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/112019210,"Victoria, Canada",91%,t,4,['phone'],-123.545252,...,1,1,0,0,1.00,Troy,1,t,1,$61.00
3950,1318259877390189592,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/32614142,"Victoria, Canada",98%,t,118,"['email', 'phone', 'work_email']",-123.369628,...,53,53,0,0,1000001.00,Elite Vacation Homes,55,t,0,$148.00

In [5]:
nulos_por_columna, nulos_totales = funcionese.identificar_nulos(df)
df

,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,longitude,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
0,19898,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/69729,Valor Nulo,Valor Nulo,f,6,"['email', 'phone']",-123.339770,...,1,0,1,0,1000001.00,Ryan,1,Valor Nulo,0,Valor Nulo
1,41168,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/173169,"Victoria, Canada",99%,t,6,"['email', 'phone']",-123.370650,...,3,3,0,0,0.50,Ocean Island Garden Suites,3,t,70,"$9,999.00"
2,83515,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/455118,"British Columbia, Canada",97%,t,4,"['email', 'phone']",-123.499960,...,2,2,0,0,0.89,Celia,2,t,148,$175.00
3,168460,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/802981,"Victoria, Canada",Valor Nulo,f,3,"['email', 'phone', 'work_email']",-123.367900,...,1,1,0,0,0.42,Deborah,1,t,64,$200.00
4,185732,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/880366,"Victoria, Canada",0%,f,3,"['email', 'phone', 'work_email']",-123.463570,...,3,0,3,0,0.32,Peter,3,t,52,$199.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3946,1315368084757533488,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/548256873,Valor Nulo,100%,Valor Nulo,6,"['email', 'phone']",-124.402109,...,3,3,0,0,1000001.00,Swell West,6,t,0,$263.00
3947,1316608634341666791,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/668062525,Valor Nulo,Valor Nulo,f,1,"['email', 'phone']",-123.414387,...,1,1,0,0,1000001.00,Charlotte Jane,1,t,0,$128.00
3948,1317141084646533661,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/290549710,"Victoria, Canada",Valor Nulo,f,1,"['email', 'phone']",-123.395233,...,1,1,0,0,1000001.00,Majachani,1,Valor Nulo,0,$98.00
3949,1318221712246054906,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/112019210,"Victoria, Canada",91%,t,4,['phone'],-123.545252,...,1,1,0,0,1.00,Troy,1,t,1,$61.00
3950,1318259877390189592,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/32614142,"Victoria, Canada",98%,t,118,"['email', 'phone', 'work_email']",-123.369628,...,53,53,0,0,1000001.00,Elite Vacation Homes,55,t,0,$148.00

In [6]:
df = funcionese.identificar_atipicos(df)
df

/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"
/Users/ruch/Desktop/MODULOS/ALFREDO/funcionese.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Valor Atípico' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[col] < limite_inferior) | (df[col] > limite_superior), col] = "Valor Atípico"

,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,longitude,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
0,19898,20241200000000.0,29/12/24,https://www.airbnb.com/users/show/69729,Valor Nulo,Valor Nulo,f,6,"['email', 'phone']",-123.33977,...,1,0,Valor Atípico,0,Valor Atípico,Ryan,1,Valor Nulo,0,Valor Nulo
1,41168,20241200000000.0,29/12/24,https://www.airbnb.com/users/show/173169,"Victoria, Canada",99%,t,6,"['email', 'phone']",-123.37065,...,3,3,0,0,0.5,Ocean Island Garden Suites,3,t,70,"$9,999.00"
2,83515,20241200000000.0,29/12/24,https://www.airbnb.com/users/show/455118,"British Columbia, Canada",97%,t,4,"['email', 'phone']",-123.49996,...,2,2,0,0,0.89,Celia,2,t,148,$175.00
3,168460,20241200000000.0,29/12/24,https://www.airbnb.com/users/show/802981,"Victoria, Canada",Valor Nulo,f,3,"['email', 'phone', 'work_email']",-123.3679,...,1,1,0,0,0.42,Deborah,1,t,64,$200.00
4,185732,20241200000000.0,29/12/24,https://www.airbnb.com/users/show/880366,"Victoria, Canada",0%,f,3,"['email', 'phone', 'work_email']",-123.46357,...,3,0,Valor Atípico,0,0.32,Peter,3,t,52,$199.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3946,1315368084757533488,20241200000000.0,29/12/24,https://www.airbnb.com/users/show/548256873,Valor Nulo,100%,Valor Nulo,6,"['email', 'phone']",Valor Atípico,...,3,3,0,0,Valor Atípico,Swell West,6,t,0,$263.00
3947,1316608634341666791,20241200000000.0,29/12/24,https://www.airbnb.com/users/show/668062525,Valor Nulo,Valor Nulo,f,1,"['email', 'phone']",-123.414387,...,1,1,0,0,Valor Atípico,Charlotte Jane,1,t,0,$128.00
3948,1317141084646533661,20241200000000.0,29/12/24,https://www.airbnb.com/users/show/290549710,"Victoria, Canada",Valor Nulo,f,1,"['email', 'phone']",-123.395233,...,1,1,0,0,Valor Atípico,Majachani,1,Valor Nulo,0,$98.00
3949,1318221712246054906,20241200000000.0,29/12/24,https://www.airbnb.com/users/show/112019210,"Victoria, Canada",91%,t,4,['phone'],-123.545252,...,1,1,0,0,1.0,Troy,1,t,1,$61.00
3950,1318259877390189592,20241200000000.0,29/12/24,https://www.airbnb.com/users/show/32614142,"Victoria, Canada",98%,t,Valor Atípico,"['email', 'phone', 'work_email']",-123.369628,...,Valor Atípico,Valor Atípico,0,0,Valor Atípico,Elite Vacation Homes,Valor Atípico,t,0,$148.00

In [7]:
df.to_csv("Victoria_BC_procesado.csv", index=False)